# Module manifest for module 'AzBuilder'
# Generated by: Lage Berger Jensen
# Generated on: 04.03.2021

@{
    RootModule        = 'AzBuilder.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = 'd730c1d2-10ae-43f7-bc90-c1b822b2c46e'
    Author            = 'Lage Berger Jensen'
    CompanyName       = ''
    Copyright         = '(c) 2021 Lage Berger Jensen. All rights reserved.'
    Description       = 'Provision your own ARM templates in a hierarchical and consistant manner.'
    FunctionsToExport = @(
        'Build-Template',
        'Invoke-Deployment',
        'Move-Template'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    RequiredModules = @(
        'Az.Resources'
    )
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            Tags = @(
                'Azure',
                'ARM template',
                'Deploy'
            )
            LicenseUri = 'https://github.com/lagebj/AzBuilder/blob/master/LICENSE'
            ProjectUri = 'https://github.com/lagebj/AzBuilder'
            # IconUri = ''
            ReleaseNotes = 'https://github.com/lagebj/AzBuilder/blob/master/ReleaseNotes.md'
        }
    }
    # HelpInfoURI = ''
    DefaultCommandPrefix = 'AzBuilder'
}
